version: '3'

services:
  web:
    build: .
    #command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
    volumes:
      - ./app:/app
      - ./data/web/static:/data/web/static/
      - ./data/web/media:/data/web/media/
      - ./data/web/midia_videos:/data/web/midia_videos/      
    ports:
      - "8000:8000"
    env_file:
      - ./dotenv_files/.env
    depends_on:
      - my-postgres

  my-postgres:
    container_name: my-postgres
    image: postgres:13-alpine
    volumes:
      - ./data/postgres/data:/var/lib/postgresql/data/
    env_file:
      - ./dotenv_files/.env